"""
RADIO PACKET FORMAT DOCUMENTATION
==================================

Date: January 5, 2026
Source: 6-hour radio log from COM7 (Laird RM024125C30, Channel 76)
Validation: Compared against OI-7032 Modbus data (COM10, Slave ID 3)

PACKET STRUCTURE (Verified)
----------------------------

Total packet length: 24 bytes typical

Byte Offset | Field              | Format           | Notes
------------|--------------------|-----------------|--------------------------
[0-1]       | Transmitter Addr   | 16-bit BE       | Usually 0x8111 (33041)
[2]         | Protocol           | 8-bit           | 0x00 = Field Data (most common)
            |                    |                 | 0x01 = Standard
            |                    |                 | 0x02/0x07 = Other
[3]         | Sequence/Flags     | 8-bit           | Varies per packet
[4-7]       | Unknown            | 4 bytes         | Possibly timestamp or padding
            |                    |                 | Common pattern: e0 88 49 00 or e0 88 2b 00
[8]         | Channel Number ✓   | 8-bit           | OI-7032 channel (1-32)
[9]         | Unknown            | 8-bit           | Always 0x81 in field data
[10-13]     | Reading ✓          | Float32 BE      | Sensor reading (ppm, %, etc.)
[14+]       | Additional Data    | Variable        | Gas type, battery, fault, etc.

VALIDATION RESULTS
------------------

7032 Modbus Data:
  Channel 5 (Radio Address 6): Reading 1.00, LEL (Combustible)
  Channel 20 (Radio Address 21): Reading 6.00, VOC (Volatile Organic Compounds)

Radio Log Data:
  ✓ Found 183 packets with Channel 5, Reading ~1.0
  ✓ Found 248 packets with Channel 20, Reading ~6.0

EXAMPLE PACKETS
---------------

1. Channel 5, Reading 1.00 (LEL):
   Hex: 8111000fe088490005813f80000000240300ece08829462f
   
   [0-1]  81 11      Transmitter: 33041 (0x8111)
   [2]    00         Protocol: 0 (Field Data)
   [3]    0f         Sequence: 15
   [4-7]  e0884900   Unknown
   [8]    05         Channel: 5 ✓
   [9]    81         Unknown (always 0x81)
   [10-13] 3f800000  Reading: 1.00 ✓
   [14+]  ...        Additional data

2. Channel 20, Reading 6.00 (VOC):
   Hex: 81110014e0884900148140c0000020270780e3c8b1bc34af
   
   [0-1]  81 11      Transmitter: 33041 (0x8111)
   [2]    00         Protocol: 0 (Field Data)
   [3]    14         Sequence: 20
   [4-7]  e0884900   Unknown
   [8]    14         Channel: 20 (0x14) ✓
   [9]    81         Unknown (always 0x81)
   [10-13] 40c00000  Reading: 6.00 ✓
   [14+]  ...        Additional data

CRITICAL FINDINGS
-----------------

1. ✓ READING OFFSET CORRECTED:
   - Previous analysis used bytes [3-6] for reading → ALL ZEROS
   - Correct offset is bytes [10-13] → VALID READINGS (1.0, 6.0, etc.)
   
2. ✓ CHANNEL NUMBER IDENTIFIED:
   - Byte [8] contains the OI-7032 channel number (1-32)
   - This maps to the receiver's channel configuration
   
3. ✓ TRANSMITTER ADDRESS:
   - Byte [0-1] contains transmitter radio address (0x8111 = 33041)
   - This is NOT the sensor/channel address
   - All packets in this log come from same transmitter
   
4. ✓ PROTOCOL 0 IS VALID:
   - 5,328 out of 6,181 packets use Protocol 0 (Field Data)
   - This is an undocumented but common protocol type
   
5. ⚠ ADDITIONAL FIELDS NEED MAPPING:
   - Gas type, battery voltage, fault codes at different offsets than Gen2
   - Bytes [14+] contain additional sensor data
   - Need to identify correct byte positions for these fields

STATISTICS FROM 6-HOUR LOG
--------------------------

Total Packets: 6,181
Protocol 0 (Field Data): 5,328 packets (86.2%)
Protocol 1: 2 packets
Protocol 2: 2 packets
Protocol 7: 1 packets

Unique Transmitters: 1 (address 33041)
Active Channels Found:
  - Channel 5: 183 readings (~1.0 LEL)
  - Channel 20: 248 readings (~6.0 VOC)
  - Plus ~24 other channels with various readings

RECOMMENDATIONS
---------------

1. Update all radio parsing code to use:
   - Byte [8] for channel number
   - Bytes [10-13] for reading (Float32 big-endian)
   
2. Map remaining fields at bytes [14+]:
   - Identify gas type offset
   - Identify battery voltage offset
   - Identify fault code offset
   - Identify sensor mode/type offset
   
3. Consider Protocol 0 as standard field format:
   - Accept Protocol 0 in all parsers
   - Document as "Field Data" protocol
   
4. Validate with other transmitters:
   - This log only has transmitter 0x8111
   - Test with other transmitter addresses if available

NEXT STEPS
----------

1. ✓ COMPLETED: Identified correct reading offset [10-13]
2. ✓ COMPLETED: Verified against 7032 Modbus data
3. TODO: Map bytes [14+] for gas type, battery, fault codes
4. TODO: Update production parser with corrected structure
5. TODO: Test with additional sensor data if available

---
This documentation was generated by comparing 6-hour radio logs against
OI-7032 Modbus ground truth data. The reading offset correction was
validated by matching 183 packets (reading 1.0) and 248 packets (reading 6.0)
against known sensor values from the OI-7032 controller.
"""

if __name__ == "__main__":
    print(__doc__)
