# ESPHome Configuration for ESP32 + MAX485
# OI-7530/7010 Modbus to MQTT Bridge via WiFi with Bluetooth Proxy

substitutions:
  device_name: teleproject32
  friendly_name: "TeleProject Gas Monitor"
  modbus_uart_tx: GPIO17
  modbus_uart_rx: GPIO16
  max485_de: GPIO4
  max485_re: GPIO4

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino  # Changed to arduino for better Bluetooth support

# Enable logging
logger:
  level: INFO
  baud_rate: 0  # Disable UART logging to free up pins for Modbus

# Enable Home Assistant API
api:
  encryption:
    key: "Gmojhn+4oSNjevz5/EwgqvL3Ws9pfzUQJZ//OGXxWoQ="

ota:
  - platform: esphome
    password: "d811525e8b1a574d633b4b57a90c2eef"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Teleproject32 Fallback Hotspot"
    password: "password"

captive_portal:

# Enable Bluetooth Proxy
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

# UART for Modbus communication
uart:
  id: mod_bus
  tx_pin: ${modbus_uart_tx}
  rx_pin: ${modbus_uart_rx}
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

# Modbus controller
modbus:
  id: modbus1
  uart_id: mod_bus
  flow_control_pin: ${max485_de}  # DE and RE pins on MAX485

modbus_controller:
  - id: oi7530
    address: 0x1  # Modbus slave address
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s

# Enable MQTT (optional, for direct MQTT publishing)
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# Sensor definitions - Channel readings (32-bit floats)
sensor:
  # WiFi signal strength
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  # Channel 1 Reading
  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 1"
    address: 0x21  # Decimal 33
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2
    
  # Channel 2 Reading
  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 2"
    address: 0x23  # Decimal 35
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2
  
  # Channel 3 Reading
  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 3"
    address: 0x25  # Decimal 37
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2
  
  # Channel 4 Reading
  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 4"
    address: 0x27  # Decimal 39
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  # Channel 5-32 (add as needed following the pattern)
  # Channel N address = 0x21 + (N-1)*2
  
  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 5"
    address: 0x29
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 6"
    address: 0x2B
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 7"
    address: 0x2D
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 8"
    address: 0x2F
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 9"
    address: 0x31
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 10"
    address: 0x33
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 11"
    address: 0x35
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 12"
    address: 0x37
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 13"
    address: 0x39
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 14"
    address: 0x3B
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 15"
    address: 0x3D
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 16"
    address: 0x3F
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 17"
    address: 0x41
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 18"
    address: 0x43
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 19"
    address: 0x45
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 20"
    address: 0x47
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 21"
    address: 0x49
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 22"
    address: 0x4B
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 23"
    address: 0x4D
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 24"
    address: 0x4F
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 25"
    address: 0x51
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 26"
    address: 0x53
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 27"
    address: 0x55
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 28"
    address: 0x57
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 29"
    address: 0x59
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 30"
    address: 0x5B
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 31"
    address: 0x5D
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: oi7530
    name: "${friendly_name} Channel 32"
    address: 0x5F
    register_type: holding
    value_type: FP32
    unit_of_measurement: "ppm"
    device_class: gas
    accuracy_decimals: 2

# Text sensors for device info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"

# Binary sensors for status
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

# Buttons for control
button:
  - platform: restart
    name: "${friendly_name} Restart"
    